<a href="https://colab.research.google.com/github/joseaureliok/soulcode-martech-bootcamp-ad/blob/notebooks_aulas/atividades-projetos/01_projeto_AD2_squad13_desgaste.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PROJETO 01**


#### Bootcamp Martech em Análise de Dados - AD2
##### SoulCode Academy
##### Professores:
                Franciane Rodrigues
                Douglas Ribeiro
                Jonatas Carneiro

##### Acadêmicos - Grupo 13:
                Vanessa
                Victor Gaspar
                Rodolfo
                Gabriel Henrique
                Carlos Silva
                José Aurelio

### **CONTEXTO**
A empresa XPTO está preocupada com a retenção de talentos na companhia e está realizando uma análise descritiva de uma série de atributos dos funcionários tendo como principal objetivo descobrir possíveis relações (*e até correlações*) que expliquem o **nível de desgaste dos funcionários** com a empresa.
        
        variável desgaste com **valor = sim** ▶ representa os funcionários que pediram demissão e saíram da empresa por se sentirem desgastados com a XPTO
        
        variável com **valor = não** ▶ representa os funcionários que continuam na empresa.

### **OBJETIVO**:
Explorar (*por meio das técnicas de gestão de projetos e análise exploratória de dados aprendidas até o momento no bootcamp*) algumas das **possíveis relações e insights que se podem obter a partir da base de dados**. Use o poder de síntese do grupo para encontrar e apresentar apenas os insights que na visão do grupo realmente possam ajudar a empresa a atingir seus objetivos com essa análise (*lembrando que o principal objetivo é ter um ambiente em que os funcionários não se sintam desgastados com a XPTO*)

### **REQUISITOS OBRIGATÓRIOS:**
1.   Medidas de estatística descritiva (**tendência central, dispersão, separatrizes e associação**) de pelo menos **4 atributos** que possam ajudar com insights relevantes para a empresa;
2.   Pelo menos **três distribuições de frequência** para atributos diferentes, sendo **obrigatoriamente** *atributos quantitativos e qualitativos*, lembrando que para atributos quantitativos as distribuições de frequência dever ser agrupadas por faixas de valores.
3. **Gráficos** adequados para cada atributo escolhido pelo grupo, podendo ser mais um gráfico diferente por atributo escolhido.
4. **Relatório** em slides (google apresentações, Power point ou canva) deverá ser anexado apenas um relatório por grupo.


### **BRAINSTORMING**

#### **Metodologia adotada KDD**
- não necessita de análise em tempo real
- é um processo iterativo
- os atributos podem ser fracionados e dividas as tarefas

#### **Escolha de ferramentas**
- extração de dados estatísticos no Colab
- trabalhar com Excel para interpretação dos dados

#### **Divisão de tarefas** [*integrante | atributo*]
- Vanessa - QTDE DE TREINAMENTOS REALIZADOS NO ÚLTIMO ANO (quantitativo)
- Gabriel  - CARGO (qualitativo)
- Victor - DISTÂNCIA DE CASA (quantitativo)
- Rodolfo -  TOTAL DE ANOS TRABALHADOS NA EMPRESA (quantitativo)
- José - SALÁRIO MENSAL (quantitativo)
- Carlos - *pendente*

In [ ]:
# importando bibliotecas
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

import pandas as pd

In [ ]:
# criando autenticaçao para o Google Drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [ ]:
# conectando ao link do arquivo do Google Drive
link = 'https://drive.google.com/file/d/1CGPtN9hf2BMDxkEL5VUZIhjXdl7fETW_/view?usp=drive_link'

id = link.split("/")[-2]

downloaded = drive.CreateFile({'id':id})
downloaded.GetContentFile('dataset_projeto01.csv')

In [ ]:
# lendo base de dados
df_base = pd.read_csv('dataset_projeto01.csv')

In [ ]:
# exibindo base de dados
display(df_base)

,Idade,Desgaste,Viagem de negócios,Diárias recebidas,Departamento,Distância de Casa,Escolaridade,Área de Formação,Número de contratos de trabalho na empresa,ID Funcionário,...,Satisfação nas relações Não trabalho,Jornada padrão de trabalho,opção de remaunração variável em ações,Total de anos trabalhados,Qtde de treinamentos realizados no último ano,Equilíbrio vida trabalho,Total de anos trabalhados na empresa,Anos trabalhados na função atual,Anos desde a última promoção,Anos trabalhando com o atual gestor
0,41,Sim,Viaja raramente,1102,Vendas,1,2,Ciências Humanas,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,Não,Viaja frequentemente,279,Pesquisa e Desenvolvimento,8,1,Ciências Humanas,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Sim,Viaja raramente,1373,Pesquisa e Desenvolvimento,2,2,Outras,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,Não,Viaja frequentemente,1392,Pesquisa e Desenvolvimento,3,4,Ciências Humanas,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,Não,Viaja raramente,591,Pesquisa e Desenvolvimento,2,1,Ciências Médicas,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,Não,Viaja frequentemente,884,Pesquisa e Desenvolvimento,23,2,Ciências Médicas,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,Não,Viaja raramente,613,Pesquisa e Desenvolvimento,6,1,Ciências Médicas,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,Não,Viaja raramente,155,Pesquisa e Desenvolvimento,4,3,Ciências Humanas,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,Não,Viaja frequentemente,1023,Vendas,2,3,Ciências Médicas,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,Não,Viaja raramente,628,Pesquisa e Desenvolvimento,8,3,Ciências Médicas,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [ ]:
# exibindo os tipos de dados
df_base.dtypes

Idade                                              int64
Desgaste                                          object
Viagem de negócios                                object
Diárias recebidas                                  int64
Departamento                                      object
Distância de Casa                                  int64
Escolaridade                                       int64
Área de Formação                                  object
Número de contratos de trabalho na empresa         int64
ID Funcionário                                     int64
Nível de Satisfação com o ambiente de trabalho     int64
Gênero                                            object
Salário por hora                                   int64
Nível de envolvimento com o trabalho               int64
Nível hierárquico                                  int64
Cargo                                             object
Satisfação com o trabalho                          int64
Estado civil                                      object
Renda mensal                                       int64
Salário Mensal                                     int64
qtde de empresas que já trabalhou                  int64
Maior de idade                                    object
Faz hora extra                                    object
percentual de aumento de salário                   int64
score de performance                               int64
Satisfação nas relações Não trabalho               int64
Jornada padrão de trabalho                         int64
opção de remaunração variável em ações             int64
Total de anos trabalhados                          int64
Qtde de treinamentos realizados no último ano      int64
Equilíbrio vida trabalho                           int64
Total de anos trabalhados na empresa               int64
Anos trabalhados na função atual                   int64
Anos desde a última promoção                       int64
Anos trabalhando com o atual gestor                int64
dtype: object

In [ ]:
# aplicando describe no dataset
display(df_base.describe(include='all'))

,Idade,Desgaste,Viagem de negócios,Diárias recebidas,Departamento,Distância de Casa,Escolaridade,Área de Formação,Número de contratos de trabalho na empresa,ID Funcionário,...,Satisfação nas relações Não trabalho,Jornada padrão de trabalho,opção de remaunração variável em ações,Total de anos trabalhados,Qtde de treinamentos realizados no último ano,Equilíbrio vida trabalho,Total de anos trabalhados na empresa,Anos trabalhados na função atual,Anos desde a última promoção,Anos trabalhando com o atual gestor
count,1470.000000,1470,1470,1470.000000,1470,1470.000000,1470.000000,1470,1470.0,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
unique,NaN,2,3,NaN,3,NaN,NaN,6,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Não,Viaja raramente,NaN,Pesquisa e Desenvolvimento,NaN,NaN,Ciências Humanas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1233,1043,NaN,961,NaN,NaN,606,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,36.923810,NaN,NaN,802.485714,NaN,9.192517,2.912925,NaN,1.0,1024.865306,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,NaN,NaN,403.509100,NaN,8.106864,1.024165,NaN,0.0,602.024335,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,NaN,NaN,102.000000,NaN,1.000000,1.000000,NaN,1.0,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,NaN,NaN,465.000000,NaN,2.000000,2.000000,NaN,1.0,491.250000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,NaN,NaN,802.000000,NaN,7.000000,3.000000,NaN,1.0,1020.500000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,NaN,NaN,1157.000000,NaN,14.000000,4.000000,NaN,1.0,1555.750000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,NaN,NaN,1499.000000,NaN,29.000000,5.000000,NaN,1.0,2068.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [ ]:
# aplicando mediana no dataset
df_median = df_base.median()
display(df_median)

<ipython-input-8-a9e303766ba5>:2: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_median = df_base.median()

Idade                                                36.0
Diárias recebidas                                   802.0
Distância de Casa                                     7.0
Escolaridade                                          3.0
Número de contratos de trabalho na empresa            1.0
ID Funcionário                                     1020.5
Nível de Satisfação com o ambiente de trabalho        3.0
Salário por hora                                     66.0
Nível de envolvimento com o trabalho                  3.0
Nível hierárquico                                     2.0
Satisfação com o trabalho                             3.0
Renda mensal                                       4919.0
Salário Mensal                                    14235.5
qtde de empresas que já trabalhou                     2.0
percentual de aumento de salário                     14.0
score de performance                                  3.0
Satisfação nas relações Não trabalho                  3.0
Jornada padrão de trabalho                           80.0
opção de remaunração variável em ações                1.0
Total de anos trabalhados                            10.0
Qtde de treinamentos realizados no último ano         3.0
Equilíbrio vida trabalho                              3.0
Total de anos trabalhados na empresa                  5.0
Anos trabalhados na função atual                      3.0
Anos desde a última promoção                          1.0
Anos trabalhando com o atual gestor                   3.0
dtype: float64

In [ ]:
# aplicando moda no dataset
df_mode = df_base.mode("index", numeric_only=True, dropna=True)
display(df_mode.loc[0].round(2))

Idade                                               35.0
Diárias recebidas                                  691.0
Distância de Casa                                    2.0
Escolaridade                                         3.0
Número de contratos de trabalho na empresa           1.0
ID Funcionário                                       1.0
Nível de Satisfação com o ambiente de trabalho       3.0
Salário por hora                                    66.0
Nível de envolvimento com o trabalho                 3.0
Nível hierárquico                                    1.0
Satisfação com o trabalho                            4.0
Renda mensal                                      2342.0
Salário Mensal                                    4223.0
qtde de empresas que já trabalhou                    1.0
percentual de aumento de salário                    11.0
score de performance                                 3.0
Satisfação nas relações Não trabalho                 3.0
Jornada padrão de trabalho                          80.0
opção de remaunração variável em ações               0.0
Total de anos trabalhados                           10.0
Qtde de treinamentos realizados no último ano        2.0
Equilíbrio vida trabalho                             3.0
Total de anos trabalhados na empresa                 5.0
Anos trabalhados na função atual                     2.0
Anos desde a última promoção                         0.0
Anos trabalhando com o atual gestor                  2.0
Name: 0, dtype: float64

In [ ]:
# encontrado a variância do conjunto de dados
df_variancia = df_base.var()
display(df_variancia.round(2))

<ipython-input-10-4a273573a650>:2: FutureWarning: The default value of numeric_only in DataFrame.var is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_variancia = df_base.var()

Idade                                                   83.46
Diárias recebidas                                   162819.59
Distância de Casa                                       65.72
Escolaridade                                             1.05
Número de contratos de trabalho na empresa               0.00
ID Funcionário                                      362433.30
Nível de Satisfação com o ambiente de trabalho           1.19
Salário por hora                                       413.61
Nível de envolvimento com o trabalho                     0.51
Nível hierárquico                                        1.23
Satisfação com o trabalho                                1.22
Renda mensal                                      22164857.07
Salário Mensal                                    50662878.17
qtde de empresas que já trabalhou                        6.24
percentual de aumento de salário                        13.40
score de performance                                     0.13
Satisfação nas relações Não trabalho                     1.17
Jornada padrão de trabalho                               0.00
opção de remaunração variável em ações                   0.73
Total de anos trabalhados                               60.54
Qtde de treinamentos realizados no último ano            1.66
Equilíbrio vida trabalho                                 0.50
Total de anos trabalhados na empresa                    37.53
Anos trabalhados na função atual                        13.13
Anos desde a última promoção                            10.38
Anos trabalhando com o atual gestor                     12.73
dtype: float64

In [ ]:
# encontrando desvio absoluto
df_desv_abs = df_base.mad()
display (df_desv_abs)

<ipython-input-11-db1437896d59>:2: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  df_desv_abs = df_base.mad()

Idade                                                7.409796
Diárias recebidas                                  350.253722
Distância de Casa                                    6.572743
Escolaridade                                         0.792710
Número de contratos de trabalho na empresa           0.000000
ID Funcionário                                     522.405076
Nível de Satisfação com o ambiente de trabalho       0.947116
Salário por hora                                    17.656401
Nível de envolvimento com o trabalho                 0.567767
Nível hierárquico                                    0.832475
Satisfação com o trabalho                            0.957221
Renda mensal                                      3631.446085
Salário Mensal                                    6188.083697
qtde de empresas que já trabalhou                    2.059758
percentual de aumento de salário                     3.055173
score de performance                                 0.260210
Satisfação nas relações Não trabalho                 0.936585
Jornada padrão de trabalho                           0.000000
opção de remaunração variável em ações               0.681547
Total de anos trabalhados                            6.034189
Qtde de treinamentos realizados no último ano        0.974344
Equilíbrio vida trabalho                             0.547972
Total de anos trabalhados na empresa                 4.471687
Anos trabalhados na função atual                     3.040922
Anos desde a última promoção                         2.346894
Anos trabalhando com o atual gestor                  3.025372
dtype: float64

In [ ]:
# encontrando a covarância
df_covariancia = df_base.cov()
display (df_covariancia)

<ipython-input-12-202fb8953d81>:2: FutureWarning: The default value of numeric_only in DataFrame.cov is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_covariancia = df_base.cov()

,Idade,Diárias recebidas,Distância de Casa,Escolaridade,Número de contratos de trabalho na empresa,ID Funcionário,Nível de Satisfação com o ambiente de trabalho,Salário por hora,Nível de envolvimento com o trabalho,Nível hierárquico,...,Satisfação nas relações Não trabalho,Jornada padrão de trabalho,opção de remaunração variável em ações,Total de anos trabalhados,Qtde de treinamentos realizados no último ano,Equilíbrio vida trabalho,Total de anos trabalhados na empresa,Anos trabalhados na função atual,Anos desde a última promoção,Anos trabalhando com o atual gestor
Idade,83.455049,39.298434,-0.124873,1.946390,0.0,-55.797199,0.101319,4.249207,0.193841,5.153276,...,0.528776,0.0,0.291977,48.361684,-0.231093,-0.138695,17.423359,7.046750,6.373743,6.587332
Diárias recebidas,39.298434,162819.593737,-16.308004,-6.945424,0.0,-12386.713294,8.095750,171.325275,13.246309,1.324944,...,3.423048,0.0,14.489565,45.570709,1.275892,-10.789322,-84.187085,14.520296,-43.206982,-37.957055
Distância de Casa,-0.124873,-16.308004,65.721251,0.174705,0.0,160.649502,-0.142451,5.564006,0.050667,0.047586,...,0.057478,0.0,0.309961,0.291951,-0.386118,-0.152094,0.472219,0.553521,0.261991,0.416715
Escolaridade,1.946390,-6.945424,0.174705,1.048914,0.0,25.939251,-0.030370,0.351812,0.030927,0.115170,...,-0.010097,0.0,0.016076,1.181612,-0.033143,0.007105,0.433659,0.223515,0.179056,0.252390
Número de contratos de trabalho na empresa,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ID Funcionário,-55.797199,-12386.713294,160.649502,25.939251,0.0,362433.299749,11.595582,401.108401,-2.950629,-12.341279,...,-45.473775,0.0,31.920482,-67.289749,18.320126,4.384426,-41.458396,-18.357800,-17.496817,-19.755358
Nível de Satisfação com o ambiente de trabalho,0.101319,8.095750,-0.142451,-0.030370,0.0,11.595582,1.194829,-1.099764,-0.006438,0.001466,...,0.009059,0.0,0.003197,-0.022905,-0.027283,0.021335,0.009761,0.071317,0.057040,-0.019496
Salário por hora,4.249207,171.325275,5.564006,0.351812,0.0,401.108401,-1.099764,413.613130,0.598640,-0.657943,...,0.008395,0.0,0.847436,-0.523681,-0.188890,-0.059181,-2.526920,-1.840829,-1.814182,-1.492576
Nível de envolvimento com o trabalho,0.193841,13.246309,0.050667,0.030927,0.0,-2.950629,-0.006438,0.598640,0.506319,-0.009948,...,0.026386,0.0,0.013049,-0.030634,-0.014071,-0.007348,-0.093097,0.022473,-0.055454,0.065951
Nível hierárquico,5.153276,1.324944,0.047586,0.115170,0.0,-12.341279,0.001466,-0.657943,-0.009948,1.225316,...,0.025901,0.0,0.013190,6.737044,-0.025961,0.029574,3.626435,1.561913,1.262322,1.482250
Satisfação com o trabalho,-0.049285,13.604357,-0.032802,-0.012759,0.0,-30.705067,-0.008179,-1.591394,-0.016853,-0.002373,...,-0.014850,0.0,0.010046,-0.173208,-0.008217,-0.015161,-0.025693,-0.009209,-0.064728,-0.108830
Renda mensal,21412.198982,14641.125975,-649.386355,457.874204,0.0,-42028.530023,-32.210416,-1642.662382,-51.159481,4952.416922,...,131.703156,0.0,21.693112,28312.303770,-131.935513,102.053699,14833.730990,6205.846259,5233.677307,5780.054075
Salário Mensal,1823.988823,-92428.502266,1585.264627,-190.148240,0.0,54198.679015,292.537298,-2253.435604,-82.667086,311.714963,...,-31.439933,0.0,-208.164513,1464.435332,13.461200,40.043086,-1031.535222,-330.479133,35.937006,-933.244190
qtde de empresas que já trabalhou,6.837739,38.457493,-0.592359,0.323165,0.0,-1.881380,0.034389,1.192719,0.026684,0.394036,...,0.142425,0.0,0.064016,4.618854,-0.212734,-0.014764,-1.812334,-0.821380,-0.296339,-0.983301
percentual de aumento de salário,0.121489,33.529204,1.193809,-0.041648,0.0,-28.520432,-0.126824,-0.709657,-0.044805,-0.140705,...,-0.160226,0.0,0.023476,-0.586872,-0.024636,-0.008480,-0.807021,-0.020156,-0.261286,-0.156517
score de performance,0.006276,0.068910,0.079300,-0.009068,0.0,-4.422436,-0.011654,-0.020430,-0.007464,-0.008476,...,-0.012231,0.0,0.001078,0.018933,-0.007247,0.000656,0.007594,0.045738,0.020808,0.029389
Satisfação nas relações Não trabalho,0.528776,3.423048,0.057478,-0.010097,0.0,-45.473775,0.009059,0.008395,0.026386,0.025901,...,1.169013,0.0,-0.042335,0.202360,0.003480,0.014975,0.128287,-0.059242,0.116692,-0.003347
Jornada padrão de trabalho,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
opção de remaunração variável em ações,0.291977,14.489565,0.309961,0.016076,0.0,31.920482,0.003197,0.847436,0.013049,0.013190,...,-0.042335,0.0,0.726035,0.067200,0.012385,0.002485,0.078607,0.156884,0.039408,0.075091
Total de anos trabalhados,48.361684,45.570709,0.291951,1.181612,0.0,-67.289749,-0.022905,-0.523681,-0.030634,6.737044,...,0.202360,0.0,0.067200,60.540563,-0.357740,0.005539,29.942577,12.978065,10.151009,12.748396
Qtde de treinamentos realizados no último ano,-0.231093,1.275892,-0.386118,-0.033143,0.0,18.320126,-0.027283,-0.188890,-0.014071,-0.025961,...,0.003480,0.0,0.012385,-0.357740,1.662219,0.025569,0.028188,-0.026801,-0.008586,-0.018841
Equilíbrio vida trabalho,-0.138695,-10.789322,-0.152094,0.007105,0.0,4.384426,0.021335,-0.059181,-0.007348,0.029574,...,0.014975,0.0,0.002485,0.005539,0.025569,0.499108,0.052325,0.127616,0.020355,0.006956
Total de anos trabalhados na empresa,17.423359,-84.187085,0.472219,0.433659,0.0,-41.458396,0.009761,-2.526920,-0.093097,3.626435,...,0.128287,0.0,0.078607,29.942577,0.028188,0.052325,37.534310,16.842239,12.208813,16.815196
Anos trabalhados na função atual,7.046750,14.520296,0.553521,0.223515,0.0,-18.357800,0.071317,-1.840829,0.022473,1.561913,...,-0.059242,0.0,0.156884,12.978065,-0.026801,0.127616,16.842239,13.127122,6.398725,9.235198
Anos desde a última promoção,6.373743,-43.206982,0.261991,0.179056,0.0,-17.496817,0.057040,-1.814182,-0.055454,1.262322,...,0.116692,0.0,0.039408,10.151009,-0.008586,0.020355,12.208813,6.398725,10.384057,5.866587
Anos trabalhando com o atual gestor,6.587332,-37.957055,0.416715,0.252390,0.0,-19.755358,-0.019496,-1.492576,0.065951,1.482250,...,-0.003347,0.0,0.075091,12.748396,-0.018841,0.006956,16.815196,9.235198,5.866587,12.731595

In [ ]:
# encontrando correlação
df_correlacao = df_base.corr()
df_correlacao

<ipython-input-52-90e719ca7502>:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_correlacao = df_base.corr()

,Idade,Diárias recebidas,Distância de Casa,Escolaridade,Número de contratos de trabalho na empresa,ID Funcionário,Nível de Satisfação com o ambiente de trabalho,Salário por hora,Nível de envolvimento com o trabalho,Nível hierárquico,...,Satisfação nas relações Não trabalho,Jornada padrão de trabalho,opção de remaunração variável em ações,Total de anos trabalhados,Qtde de treinamentos realizados no último ano,Equilíbrio vida trabalho,Total de anos trabalhados na empresa,Anos trabalhados na função atual,Anos desde a última promoção,Anos trabalhando com o atual gestor
Idade,1.000000,0.010661,-0.001686,0.208034,NaN,-0.010145,0.010146,0.022871,0.029820,0.509604,...,0.053535,NaN,0.037510,0.680381,-0.019621,-0.021490,0.311309,0.212901,0.216513,0.202089
Diárias recebidas,0.010661,1.000000,-0.004985,-0.016806,NaN,-0.050990,0.018355,0.020877,0.046135,0.002966,...,0.007846,NaN,0.042143,0.014515,0.002453,-0.037848,-0.034055,0.009932,-0.033229,-0.026363
Distância de Casa,-0.001686,-0.004985,1.000000,0.021042,NaN,0.032916,-0.016075,0.033747,0.008783,0.005303,...,0.006557,NaN,0.044872,0.004628,-0.036942,-0.026556,0.009508,0.018845,0.010029,0.014406
Escolaridade,0.208034,-0.016806,0.021042,1.000000,NaN,0.042070,-0.027128,0.016891,0.042438,0.101589,...,-0.009118,NaN,0.018422,0.148280,-0.025100,0.009819,0.069114,0.060236,0.054254,0.069065
Número de contratos de trabalho na empresa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ID Funcionário,-0.010145,-0.050990,0.032916,0.042070,NaN,1.000000,0.017621,0.032761,-0.006888,-0.018519,...,-0.069861,NaN,0.062227,-0.014365,0.023603,0.010309,-0.011240,-0.008416,-0.009019,-0.009197
Nível de Satisfação com o ambiente de trabalho,0.010146,0.018355,-0.016075,-0.027128,NaN,0.017621,1.000000,-0.049471,-0.008278,0.001212,...,0.007665,NaN,0.003432,-0.002693,-0.019359,0.027627,0.001458,0.018007,0.016194,-0.004999
Salário por hora,0.022871,0.020877,0.033747,0.016891,NaN,0.032761,-0.049471,1.000000,0.041367,-0.029226,...,0.000382,NaN,0.048903,-0.003309,-0.007204,-0.004119,-0.020281,-0.024982,-0.027682,-0.020568
Nível de envolvimento com o trabalho,0.029820,0.046135,0.008783,0.042438,NaN,-0.006888,-0.008278,0.041367,1.000000,-0.012630,...,0.034297,NaN,0.021523,-0.005533,-0.015338,-0.014617,-0.021355,0.008717,-0.024184,0.025976
Nível hierárquico,0.509604,0.002966,0.005303,0.101589,NaN,-0.018519,0.001212,-0.029226,-0.012630,1.000000,...,0.021642,NaN,0.013984,0.782208,-0.018191,0.037818,0.534739,0.389447,0.353885,0.375281
Satisfação com o trabalho,-0.004892,0.030571,-0.003669,-0.011296,NaN,-0.046247,-0.006784,-0.070952,-0.021476,-0.001944,...,-0.012454,NaN,0.010690,-0.020185,-0.005779,-0.019459,-0.003803,-0.002305,-0.018214,-0.027656
Renda mensal,0.497855,0.007707,-0.017014,0.094961,NaN,-0.014829,-0.006259,-0.017156,-0.015271,0.950300,...,0.025873,NaN,0.005408,0.772893,-0.021736,0.030683,0.514285,0.363818,0.344978,0.344079
Salário Mensal,0.028051,-0.032182,0.027473,-0.026084,NaN,0.012648,0.037600,-0.015567,-0.016322,0.039563,...,-0.004085,NaN,-0.034323,0.026442,0.001467,0.007963,-0.023655,-0.012815,0.001567,-0.036746
qtde de empresas que já trabalhou,0.299635,0.038153,-0.029251,0.126317,NaN,-0.001251,0.012594,0.023477,0.015012,0.142501,...,0.052733,NaN,0.030075,0.237639,-0.066054,-0.008366,-0.118421,-0.090754,-0.036814,-0.110319
percentual de aumento de salário,0.003634,0.022704,0.040235,-0.011111,NaN,-0.012944,-0.031701,-0.009534,-0.017205,-0.034730,...,-0.040490,NaN,0.007528,-0.020608,-0.005221,-0.003280,-0.035991,-0.001520,-0.022154,-0.011985
score de performance,0.001904,0.000473,0.027110,-0.024539,NaN,-0.020359,-0.029548,-0.002784,-0.029071,-0.021222,...,-0.031351,NaN,0.003506,0.006744,-0.015579,0.002572,0.003435,0.034986,0.017896,0.022827
Satisfação nas relações Não trabalho,0.053535,0.007846,0.006557,-0.009118,NaN,-0.069861,0.007665,0.000382,0.034297,0.021642,...,1.000000,NaN,-0.045952,0.024054,0.002497,0.019604,0.019367,-0.015123,0.033493,-0.000867
Jornada padrão de trabalho,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
opção de remaunração variável em ações,0.037510,0.042143,0.044872,0.018422,NaN,0.062227,0.003432,0.048903,0.021523,0.013984,...,-0.045952,NaN,1.000000,0.010136,0.011274,0.004129,0.015058,0.050818,0.014352,0.024698
Total de anos trabalhados,0.680381,0.014515,0.004628,0.148280,NaN,-0.014365,-0.002693,-0.003309,-0.005533,0.782208,...,0.024054,NaN,0.010136,1.000000,-0.035662,0.001008,0.628133,0.460365,0.404858,0.459188
Qtde de treinamentos realizados no último ano,-0.019621,0.002453,-0.036942,-0.025100,NaN,0.023603,-0.019359,-0.007204,-0.015338,-0.018191,...,0.002497,NaN,0.011274,-0.035662,1.000000,0.028072,0.003569,-0.005738,-0.002067,-0.004096
Equilíbrio vida trabalho,-0.021490,-0.037848,-0.026556,0.009819,NaN,0.010309,0.027627,-0.004119,-0.014617,0.037818,...,0.019604,NaN,0.004129,0.001008,0.028072,1.000000,0.012089,0.049856,0.008941,0.002759
Total de anos trabalhados na empresa,0.311309,-0.034055,0.009508,0.069114,NaN,-0.011240,0.001458,-0.020281,-0.021355,0.534739,...,0.019367,NaN,0.015058,0.628133,0.003569,0.012089,1.000000,0.758754,0.618409,0.769212
Anos trabalhados na função atual,0.212901,0.009932,0.018845,0.060236,NaN,-0.008416,0.018007,-0.024982,0.008717,0.389447,...,-0.015123,NaN,0.050818,0.460365,-0.005738,0.049856,0.758754,1.000000,0.548056,0.714365
Anos desde a última promoção,0.216513,-0.033229,0.010029,0.054254,NaN,-0.009019,0.016194,-0.027682,-0.024184,0.353885,...,0.033493,NaN,0.014352,0.404858,-0.002067,0.008941,0.618409,0.548056,1.000000,0.510224
Anos trabalhando com o atual gestor,0.202089,-0.026363,0.014406,0.069065,NaN,-0.009197,-0.004999,-0.020568,0.025976,0.375281,...,-0.000867,NaN,0.024698,0.459188,-0.004096,0.002759,0.769212,0.714365,0.510224,1.000000

In [ ]:
# moda do atributo idade
df_mode = df_base.mode("index", numeric_only=True, dropna=True)
df_mode.loc[0][0]

35.0

In [ ]:
# criação de dataframa Salário Mensal e Desgaste
df_salm = df_base[["Salário Mensal", "Desgaste"]]
df_salm.mode()

   Salário Mensal Desgaste
0            4223      Não
1            9150      NaN

In [ ]:
df_salm.describe(include = "all").round(2)

        Salário Mensal Desgaste
count          1470.00     1470
unique             NaN        2
top                NaN      Não
freq               NaN     1233
mean          14313.10      NaN
std            7117.79      NaN
min            2094.00      NaN
25%            8047.00      NaN
50%           14235.50      NaN
75%           20461.50      NaN
max           26999.00      NaN

In [ ]:
# resultados absolutos sobre Desgates
df_salm.groupby(['Desgaste']).describe().round(2)

         Salário Mensal                                                       \
                  count      mean      std     min     25%      50%      75%
Desgaste
Não              1233.0  14265.78  7102.26  2094.0  7973.0  14120.0  20364.0
Sim               237.0  14559.31  7208.15  2326.0  8870.0  14618.0  21081.0


              max
Desgaste
Não       26997.0
Sim       26999.0

In [ ]:
df_salm.groupby(['Desgaste']).var().round(2)

          Salário Mensal
Desgaste
Não          50442107.75
Sim          51957473.48

# **CONCLUSÃO**